seed: 0
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False
use_parallel: False
run_mode: 'train'

# trainer config
trainer:
  type: ContrastiveLanguageImagePretrainTrainer
  model_name: 'qwenvl'

# dataset
train_dataset: &train_dataset
  data_loader:
    type: QwenVLDataLoader
    dataset_dir: "/data/coco2014/coco"
    image_dir: ["images"]
    stage: 1
    column_names: ["image", "text"]
    shuffle: True
    task_config:
      caption:
        annotation_files: ["annotations/coco_karpathy_train.json"]
    extra_kwargs:
      max_img_len: 5
      map_function_kwargs:
        user_role_name: <|im_start|>user
        assistant_role_name: <|im_start|>assistant
  num_parallel_workers: 8
  output_columns: [ "text", "image_start_pos"]
  column_order: [ "text", "image", "image_start_pos"]
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 1
  repeat: 1
  numa_enable: False
  prefetch_size: 30
  seed: 2022
  transforms:
    - type: RandomResizedCrop
      size: 224
      scale: [ 0.5, 1.0 ]
      interpolation: "bicubic"
    - type: RandomHorizontalFlip
    - type: ToTensor
    - type: Normalize
      mean: [ 0.48145466, 0.4578275, 0.40821073 ]
      std: [ 0.26862954, 0.26130258, 0.27577711 ]
      is_hwc: False
  text_transforms:
    type: QwenVLTransform
    max_length: 513
  tokenizer:
    type: QwenVLTokenizer

train_dataset_task:
  type: QwenVLDataset
  dataset_config: *train_dataset
# runner config
runner_config:
  epochs: 5
  batch_size: 4
  sink_mode: True
  sink_size: 2
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 65536
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.98
  eps: 1.e-6
  weight_decay: 0.1

# lr sechdule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 2.e-4
  lr_end: 1.e-6
  warmup_lr_init: 1.e-6
  warmup_steps: 500
  total_steps: -1 # -1 means it will load the total steps of the datase

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "qwen"
    save_checkpoint_steps: 10000
    keep_checkpoint_max: 3
    integrated_save: False
    async_save: False
  - type: ObsMonitor

# default parallel of device num = 8 for Atlas 800T A2
parallel_config:
  data_parallel: 8
  model_parallel: 1
  pipeline_stage: 1
  micro_batch_num: 1
  vocab_emb_dp: False
  gradient_aggregation_group: 4
# when model parallel is greater than 1, we can set micro_batch_interleave_num=2, that may accelerate the train process.
micro_batch_interleave_num: 1

# recompute config
recompute_config:
  recompute: False
  select_recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: False
  recompute_slice_activation: False

model:
  model_config:
    type: QwenVLConfig

    freeze_vision: False
    freeze_resampler: False
    freeze_llm: True

    vision_config:
      type: CLIPVisionConfig
      hidden_size: 1664
      intermediate_size: 8192
      num_hidden_layers: 48
      num_attention_heads: 16
      image_size: 224
      patch_size: 14
      hidden_act: "gelu"
      gelu_dtype: "float32"
      dropout: 0.0
      attention_dropout: 0.0
      initializer_range: 0.02
      initializer_factor: 1.0
      mlp_ratio: 4.9231

    text_config:
      type: QwenConfig
      batch_size: 1
      seq_length: 512
      hidden_size: 4096
      num_layers: 32
      num_heads: 32
      vocab_size: 151936
      intermediate_size: 11008
      rms_norm_eps: 1.0e-6
      emb_dropout_prob: 0.0
      eos_token_id: 151643
      pad_token_id: 151643
      compute_in_2d: False
      compute_dtype: "float16"
      layernorm_compute_type: "float32"
      softmax_compute_type: "float32"
      rotary_dtype: "float16"
      param_init_type: "float16"
      use_past: False
      use_flash_attention: False
      use_past_shard: False
      offset: 0
      checkpoint_name_or_path: ""
      repetition_penalty: 1
      max_decode_length: 1024
      top_k: 0
      top_p: 0.8
      do_sample: False

      # configuration items copied from Qwen
      rotary_pct: 1.0
      rotary_emb_base: 10000
      kv_channels: 128

  arch:
    type: QwenVL

# processor
processor:
  type: QwenVLProcessor
  image_processor:
    type: QwenVLImageProcessor
    image_size: 224  # input image size
  tokenizer:
    type: QwenVLTokenizer
    max_length: 32
    vocab_file: ""

# mindspore context init config
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  ascend_config:
    precision_mode: "must_keep_origin_dtype"
  max_call_depth: 10000
  max_device_memory: "58GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

# parallel context config
parallel:
  parallel_mode: 1 # 0-data parallel, 1-semi-auto parallel, 2-auto parallel, 3-hybrid parallel
  gradients_mean: False
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_config:
    save_file: "./ckpt_strategy.ckpt"
    only_trainable_params: False
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64
